export function randomSpot() {
  const x = Math.floor(Math.random() * (6 + 6) - 6);
  const y = Math.floor(Math.random() * (6 + 6) - 6);
  return { x, y };
}
//Left Wall: -7
//Bottom wall: 6
//Top Wall: -4
//Right wall: 7

export const mapData = {
  minX: -6,
  maxX: 6,
  minY: -4,
  maxY: 5,
  blockedSpaces: {
    "-3x-4": true,
    "-3x-3": true,
    "-3x-2": true,
    "-3x-1": true,
    "-3x0": true,
    "-3x1": true,
    "-2x-4": true,
    "-2x-3": true,
    "-2x-2": true,
    "-2x-1": true,
    "-2x0": true,
    "-2x1": true,
    "0x1": true,
    "4x1": true,
    "0x3": true,
    "4x3": true,
    "6x5": true,
    "6x4": true,
    "6x3": true,
    "6x2": true,
    "6x1": true,
    "6x0": true,
    "-1x-3": true,
    "0x-3": true,
    "1x-3": true,
    "2x-3": true,
    "3x-3": true,
    "4x-4": true,
    "6x-4": true,
  },
};

export function getCoordinateString(x, y) {
  return x + "x" + y;
}

export function isSolid(x, y) {
  if (
    x < mapData.minX ||
    x > mapData.maxX ||
    y < mapData.minY ||
    y > mapData.maxY
  ) {
    return true;
  }
  const coor = getCoordinateString(x, y);
  return mapData.blockedSpaces[coor];
}

export function sanitized(str) {
  //! Install sanitization dependency
  // const reg = /^[A-Za-z0-9_.'" ]*$/;
  // return reg.test(str);
  return str;
}

export const spriteFileNames = [
  "amane.png",
  "ameliaseillune.png",
  "america.png",
  "america_nyo.png",
  "america_nyo2.png",
  "america_revwar.png",
  "america_spades.png",
  "america_teen.png",
  "amimizuno.png",
  "australia.png",
  "austria.png",
  "austria_clubs.png",
  "austria_nyo.png",
  "austria_teen.png",
  "azura.png",
  "babyamerica.png",
  "babycanada.png",
  "belarus.png",
  "belarus2.png",
  "belgium.png",
  "belgium2.png",
  "blacklady.png",
  "canada.png",
  "canada_nyo.png",
  "canada_nyo2.png",
  "canada_teen.png",
  "chibitalia.png",
  "chibiusa.png",
  "chikaru.png",
  "china.png",
  "china2.png",
  "china_nyo.png",
  "china_nyo2.png",
  "china_spades.png",
  "cuba.png",
  "denmark.png",
  "egypt.png",
  "england.png",
  "england_nyo.png",
  "england_nyo2.png",
  "england_revwar.png",
  "england_spades.png",
  "england_teen.png",
  "estonia.png",
  "finland.png",
  "finland2.png",
  "florian.png",
  "france.png",
  "france_diamonds.png",
  "france_nyo.png",
  "france_nyo2.png",
  "france_teen.png",
  "germania.png",
  "germany.png",
  "germany_hearts.png",
  "germany_nyo.png",
  "germany_nyo2.png",
  "gourrygabriev.png",
  "greece.png",
  "greece_teen.png",
  "harukatenoh.png",
  "hikari.png",
  "holyromanempire.png",
  "hongkong.png",
  "hotarutomoe.png",
  "hungary.png",
  "hungary2.png",
  "hungary_clubs.png",
  "hungary_teen.png",
  "iceland.png",
  "italy_hearts.png",
  "italy_nyo.png",
  "italy_nyo2.png",
  "japan.png",
  "japan2.png",
  "japan_hearts.png",
  "japan_nyo.png",
  "japan_nyo2.png",
  "japan_teen.png",
  "kizuna.png",
  "korea.png",
  "laila.png",
  "latvia.png",
  "liechtenstein.png",
  "liechtenstein_diamonds.png",
  "liechtenstein_teen.png",
  "linainverse.png",
  "lithuania.png",
  "lithuania_teen.png",
  "makotokino.png",
  "mamoruchiba.png",
  "michirukaioh.png",
  "minakoaino.png",
  "nagaserpent.png",
  "nagisa.png",
  "nitaly.png",
  "norway.png",
  "poland.png",
  "poland_teen.png",
  "princessserenity.png",
  "prussia.png",
  "prussia_joker.png",
  "prussia_nyo.png",
  "prussia_nyo2.png",
  "queenberyl.png",
  "queenserenity.png",
  "ray.png",
  "ray_noir.png",
  "reihino.png",
  "remon.png",
  "rome.png",
  "russia.png",
  "russia_clubs.png",
  "russia_nyo.png",
  "russia_nyo2.png",
  "russia_teen.png",
  "sailorchibimoon.png",
  "sailorjupiter.png",
  "sailormars.png",
  "sailormercury.png",
  "sailormoon.png",
  "sailorneptune.png",
  "sailorpluto.png",
  "sailorsaturn.png",
  "sailorstarfighter.png",
  "sailorstarhealer.png",
  "sailorstarmaker.png",
  "sailoruranus.png",
  "sailorvenus.png",
  "sealand.png",
  "sealand_joker.png",
  "seiyakou.png",
  "setsunameioh.png",
  "seychelles.png",
  "shizuma.png",
  "sitaly.png",
  "solomon.png",
  "spain.png",
  "spain_teen.png",
  "sweden.png",
  "switzerland.png",
  "switzerland_diamonds.png",
  "switzerland_teen.png",
  "taikikou.png",
  "taiwan.png",
  "tamao.png",
  "thailand.png",
  "tibet.png",
  "turkey.png",
  "tuxedokamen.png",
  "ukraine.png",
  "ukraine2.png",
  "undefined",
  "usagitsukino.png",
  "vietnam.png",
  "xellossmetallium.png",
  "yatenkou.png",
  "yaya.png",
  "zelgadisgreywords.png",
];
